# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import worker_pb2 as worker__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in worker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkerServiceStub(object):
    """-------- service --------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartContainer = channel.unary_unary(
                '/tunix.tinyflow.worker.WorkerService/StartContainer',
                request_serializer=worker__pb2.StartContainerRequest.SerializeToString,
                response_deserializer=worker__pb2.StartContainerResponse.FromString,
                _registered_method=True)
        self.StopContainer = channel.unary_unary(
                '/tunix.tinyflow.worker.WorkerService/StopContainer',
                request_serializer=worker__pb2.StopContainerRequest.SerializeToString,
                response_deserializer=worker__pb2.Empty.FromString,
                _registered_method=True)
        self.Exec = channel.unary_stream(
                '/tunix.tinyflow.worker.WorkerService/Exec',
                request_serializer=worker__pb2.ExecRequest.SerializeToString,
                response_deserializer=worker__pb2.ExecChunk.FromString,
                _registered_method=True)
        self.WriteFile = channel.unary_unary(
                '/tunix.tinyflow.worker.WorkerService/WriteFile',
                request_serializer=worker__pb2.WriteFileRequest.SerializeToString,
                response_deserializer=worker__pb2.Empty.FromString,
                _registered_method=True)
        self.ReadFile = channel.unary_unary(
                '/tunix.tinyflow.worker.WorkerService/ReadFile',
                request_serializer=worker__pb2.ReadFileRequest.SerializeToString,
                response_deserializer=worker__pb2.FileContent.FromString,
                _registered_method=True)
        self.ListDir = channel.unary_unary(
                '/tunix.tinyflow.worker.WorkerService/ListDir',
                request_serializer=worker__pb2.ListDirRequest.SerializeToString,
                response_deserializer=worker__pb2.DirListing.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/tunix.tinyflow.worker.WorkerService/HealthCheck',
                request_serializer=worker__pb2.Empty.SerializeToString,
                response_deserializer=worker__pb2.HealthStatus.FromString,
                _registered_method=True)
        self.ReleaseAll = channel.unary_unary(
                '/tunix.tinyflow.worker.WorkerService/ReleaseAll',
                request_serializer=worker__pb2.Empty.SerializeToString,
                response_deserializer=worker__pb2.Empty.FromString,
                _registered_method=True)


class WorkerServiceServicer(object):
    """-------- service --------

    """

    def StartContainer(self, request, context):
        """Container lifecycle.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopContainer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Exec(self, request, context):
        """Execution. Streaming so long-running bash output flows in real time
        and the client can apply per-chunk timeouts without buffering whole
        stdout in worker memory.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteFile(self, request, context):
        """File ops. Used to upload patches / read evaluation output / inspect
        container filesystem.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDir(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health & lifecycle.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseAll(self, request, context):
        """ReleaseAll stops every active container; called by the pool coordinator
        when a worker is being returned to the idle pool.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartContainer': grpc.unary_unary_rpc_method_handler(
                    servicer.StartContainer,
                    request_deserializer=worker__pb2.StartContainerRequest.FromString,
                    response_serializer=worker__pb2.StartContainerResponse.SerializeToString,
            ),
            'StopContainer': grpc.unary_unary_rpc_method_handler(
                    servicer.StopContainer,
                    request_deserializer=worker__pb2.StopContainerRequest.FromString,
                    response_serializer=worker__pb2.Empty.SerializeToString,
            ),
            'Exec': grpc.unary_stream_rpc_method_handler(
                    servicer.Exec,
                    request_deserializer=worker__pb2.ExecRequest.FromString,
                    response_serializer=worker__pb2.ExecChunk.SerializeToString,
            ),
            'WriteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteFile,
                    request_deserializer=worker__pb2.WriteFileRequest.FromString,
                    response_serializer=worker__pb2.Empty.SerializeToString,
            ),
            'ReadFile': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadFile,
                    request_deserializer=worker__pb2.ReadFileRequest.FromString,
                    response_serializer=worker__pb2.FileContent.SerializeToString,
            ),
            'ListDir': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDir,
                    request_deserializer=worker__pb2.ListDirRequest.FromString,
                    response_serializer=worker__pb2.DirListing.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=worker__pb2.Empty.FromString,
                    response_serializer=worker__pb2.HealthStatus.SerializeToString,
            ),
            'ReleaseAll': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseAll,
                    request_deserializer=worker__pb2.Empty.FromString,
                    response_serializer=worker__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tunix.tinyflow.worker.WorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tunix.tinyflow.worker.WorkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerService(object):
    """-------- service --------

    """

    @staticmethod
    def StartContainer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tunix.tinyflow.worker.WorkerService/StartContainer',
            worker__pb2.StartContainerRequest.SerializeToString,
            worker__pb2.StartContainerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopContainer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tunix.tinyflow.worker.WorkerService/StopContainer',
            worker__pb2.StopContainerRequest.SerializeToString,
            worker__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Exec(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tunix.tinyflow.worker.WorkerService/Exec',
            worker__pb2.ExecRequest.SerializeToString,
            worker__pb2.ExecChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tunix.tinyflow.worker.WorkerService/WriteFile',
            worker__pb2.WriteFileRequest.SerializeToString,
            worker__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tunix.tinyflow.worker.WorkerService/ReadFile',
            worker__pb2.ReadFileRequest.SerializeToString,
            worker__pb2.FileContent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDir(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tunix.tinyflow.worker.WorkerService/ListDir',
            worker__pb2.ListDirRequest.SerializeToString,
            worker__pb2.DirListing.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tunix.tinyflow.worker.WorkerService/HealthCheck',
            worker__pb2.Empty.SerializeToString,
            worker__pb2.HealthStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tunix.tinyflow.worker.WorkerService/ReleaseAll',
            worker__pb2.Empty.SerializeToString,
            worker__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
